@startuml

title __PROJET_WARRIORS's Class Diagram__\n

  namespace com.projet_warriors {
    interface com.projet_warriors.Case {
        {abstract} + interact()
    }
  }
  

  namespace com.projet_warriors {
    class com.projet_warriors.CaseVide {
        - nom : String
        + CaseVide()
        + getNom()
        + interact()
        + setNom()
        + toString()
    }
  }
  

  namespace com.projet_warriors {
    class com.projet_warriors.Main {
        {static} + main()
    }
  }
  

  namespace com.projet_warriors {
    class com.projet_warriors.Menu {
        + Menu()
        + choixRelanceJeu()
        + chooseName()
        + createPlayerValid()
        + lanceJeu()
    }
  }
  

  namespace com.projet_warriors {
    class com.projet_warriors.PlateauJeu {
        - cases : ArrayList<Case>
        - plateau : int
        + PlateauJeu()
        + caseAt()
        + getCases()
        + getPlateau()
        + randamPlateau()
        + setCases()
        + setPlateau()
    }
  }
  

  namespace com.projet_warriors {
    class com.projet_warriors.PlayGame {
        - posPlayer : int
        + controlePos()
        + createPlayer()
        + exitJeu()
        + getPlayerHero()
        + interactionPlateau()
        + jouerFuire()
        + lanceDice()
        + play()
        + setPlayerHero()
        + statusJeu()
    }
  }
  

  com.projet_warriors.CaseVide .up.|> com.projet_warriors.Case
  com.projet_warriors.PlayGame o-- com.projet_warriors.personnages.Personnage : playerHero


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
